"""Remove sequence tables and update schema

Revision ID: 1386764ea229
Revises: 09102687a075
Create Date: 2025-08-25 05:40:07.399858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1386764ea229'
down_revision = '09102687a075'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove sequence-related tables
    op.drop_table('sequence_step')
    op.drop_table('enrollment')
    op.drop_table('sequence')
    
    # Remove sequence-related columns from message table
    op.drop_constraint('message_step_id_fkey', 'message', type_='foreignkey')
    op.drop_constraint('message_sequence_id_fkey', 'message', type_='foreignkey')
    op.drop_column('message', 'step_id')
    op.drop_column('message', 'sequence_id')
    
    # Add created_at column to message table if it doesn't exist
    op.add_column('message', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Update indexes
    op.drop_index('idx_contact_email', table_name='contact')
    op.drop_index('idx_contact_owner_id', table_name='contact')
    op.create_foreign_key(None, 'event', 'message', ['message_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_message_contact_id', table_name='message')
    op.drop_index('idx_message_owner_id', table_name='message')
    op.create_index(op.f('ix_message_contact_id'), 'message', ['contact_id'], unique=False)
    op.create_index(op.f('ix_message_owner_id'), 'message', ['owner_id'], unique=False)
    op.drop_index('idx_task_contact_id', table_name='task')
    op.drop_index('idx_task_owner_id', table_name='task')
    op.drop_index('idx_template_owner_id', table_name='template')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate indexes
    op.create_index('idx_template_owner_id', 'template', ['owner_id'], unique=False)
    op.create_index('idx_task_owner_id', 'task', ['owner_id'], unique=False)
    op.create_index('idx_task_contact_id', 'task', ['contact_id'], unique=False)
    op.drop_index(op.f('ix_message_owner_id'), table_name='message')
    op.drop_index(op.f('ix_message_contact_id'), table_name='message')
    op.create_index('idx_message_owner_id', 'message', ['owner_id'], unique=False)
    op.create_index('idx_message_contact_id', 'message', ['contact_id'], unique=False)
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_index('idx_contact_owner_id', 'contact', ['owner_id'], unique=False)
    op.create_index('idx_contact_email', 'contact', ['email'], unique=False)
    
    # Remove created_at column from message table
    op.drop_column('message', 'created_at')
    
    # Recreate sequence-related columns in message table
    op.add_column('message', sa.Column('sequence_id', sa.UUID(), nullable=True))
    op.add_column('message', sa.Column('step_id', sa.UUID(), nullable=True))
    op.create_foreign_key('message_sequence_id_fkey', 'message', 'sequence', ['sequence_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('message_step_id_fkey', 'message', 'sequence_step', ['step_id'], ['id'], ondelete='SET NULL')
    
    # Recreate sequence-related tables
    op.create_table('sequence',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sequence_owner_id', 'sequence', ['owner_id'], unique=False)
    
    op.create_table('sequence_step',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('sequence_id', sa.UUID(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('channel', sa.String(), nullable=False),
        sa.Column('template_id', sa.UUID(), nullable=True),
        sa.Column('wait_hours', sa.Integer(), nullable=False),
        sa.Column('send_window_start', sa.Time(), nullable=True),
        sa.Column('send_window_end', sa.Time(), nullable=True),
        sa.Column('throttle_per_hour', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sequence_step_sequence_id', 'sequence_step', ['sequence_id'], unique=False)
    
    op.create_table('enrollment',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('sequence_id', sa.UUID(), nullable=False),
        sa.Column('contact_id', sa.UUID(), nullable=False),
        sa.Column('owner_id', sa.UUID(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('current_step', sa.Integer(), nullable=False),
        sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['owner_id'], ['app_user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrollment_owner_id', 'enrollment', ['owner_id'], unique=False)
    # ### end Alembic commands ###
